package edu.fatec.petwise.features.medications.presentation.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import edu.fatec.petwise.features.medications.domain.models.Medication
import edu.fatec.petwise.features.medications.domain.usecases.AddMedicationUseCase
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.datetime.Clock
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

data class AddMedicationUiState(
    val isLoading: Boolean = false,
    val isSuccess: Boolean = false,
    val errorMessage: String? = null
)

class AddMedicationViewModel(
    private val addMedicationUseCase: AddMedicationUseCase
) : ViewModel() {

    private val _uiState = MutableStateFlow(AddMedicationUiState())
    val uiState: StateFlow<AddMedicationUiState> = _uiState.asStateFlow()

    fun addMedication(formData: Map<String, Any>) {
        viewModelScope.launch {
            println("Iniciando adição de novo medicamento")
            _uiState.value = _uiState.value.copy(isLoading = true, errorMessage = null)

            try {
                val medicationName = formData["medicationName"] as? String ?: ""
                val dosage = formData["dosage"] as? String ?: ""
                val frequency = formData["frequency"] as? String ?: ""
                val durationDaysStr = formData["durationDays"] as? String ?: "0"
                val startDate = formData["startDate"] as? String ?: ""
                val endDate = formData["endDate"] as? String ?: ""
                val petId = formData["petId"] as? String ?: ""
                val veterinarianId = formData["veterinarianId"] as? String ?: ""
                val prescriptionId = formData["prescriptionId"] as? String ?: ""
                val sideEffects = formData["sideEffects"] as? String ?: ""

                // Convert string to int
                val durationDays = durationDaysStr.toIntOrNull()
                if (durationDays == null || durationDays <= 0) {
                    println("Erro de validação: Duração inválida - $durationDaysStr")
                    _uiState.value = _uiState.value.copy(
                        isLoading = false,
                        errorMessage = "Duração deve ser um número válido maior que 0"
                    )
                    return@launch
                }

                // Generate current timestamp
                val now = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault()).toString()

                val medication = Medication(
                    id = "", // Will be generated by the API
                    userId = "user123", // TODO: Get from auth context
                    petId = petId,
                    veterinarianId = veterinarianId,
                    prescriptionId = prescriptionId,
                    medicationName = medicationName,
                    dosage = dosage,
                    frequency = frequency,
                    durationDays = durationDays,
                    startDate = startDate,
                    endDate = endDate,
                    sideEffects = sideEffects,
                    createdAt = now,
                    updatedAt = now
                )

                println("Salvando novo medicamento: nome=${medication.medicationName}, dosagem=${medication.dosage}")

                addMedicationUseCase(medication).fold(
                    onSuccess = { addedMedication ->
                        println("Medicamento adicionado com sucesso: ${addedMedication.medicationName} (ID: ${addedMedication.id})")
                        _uiState.value = _uiState.value.copy(
                            isLoading = false,
                            isSuccess = true,
                            errorMessage = null
                        )
                    },
                    onFailure = { error ->
                        println("Erro ao adicionar medicamento: ${error.message}")
                        _uiState.value = _uiState.value.copy(
                            isLoading = false,
                            errorMessage = error.message ?: "Erro ao adicionar medicamento"
                        )
                    }
                )
            } catch (e: Exception) {
                println("Exceção durante adição do medicamento: ${e.message}")
                _uiState.value = _uiState.value.copy(
                    isLoading = false,
                    errorMessage = e.message ?: "Erro desconhecido"
                )
            }
        }
    }

    fun clearState() {
        println("Limpando estado do AddMedicationViewModel")
        _uiState.value = AddMedicationUiState()
    }
}